### ISSUE TITLE
Manage stops

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#18]
Would be useful to know when stops have been updated. Some common uses:

* How many stops have not been updated since X date
* A list of the stops that have not been updated since X date

Might be more flexible to provide:

* How many stops were updated over a date range
* A list of stops that were updated over a date range

Or a CSV export

**Comment by sherson** [comment]
Also, related to (and arguably a duplicate of) #5

**Comment by dfaulken** [comment]
Should be branched off of the general stop management interface, which is needed here.

**Comment by dfaulken** [comment]
Rolled #5 into this

**Comment by dfaulken** [comment]
Need a general stop management interface, for admins, with the following capabilities:

+ Deactivation
+ Sorting, filtering, searching, pagination (should find an easy gem for this)
+ Report / CSV: Which stops have not been updated since X date. Report should show number (this is obvious when importing a CSV).

**Comment by dfaulken** [comment]
Regarding:

>Might be more flexible to provide:
>
>* How many stops were updated over a date range
>* A list of stops that were updated over a date range

Will implement if requested.

**Comment by sherson** [comment]
For posterity: In this week's meeting, we confirmed that this isn't needed since it can be retrieved from Hastus:

> * How many stops were updated over a date range
> * A list of stops that were updated over a date range
