### ISSUE TITLE
Mysterious Line on Mouse Hover

### ISSUE THREAD

**Issue by mboneil10** [umts/stop-project#25]
Mouse hover produces black line in some cases

<img width="920" alt="screen shot 2018-04-10 at 3 31 02 pm" src="https://user-images.githubusercontent.com/19267771/38579217-53239ae4-3cd4-11e8-8d13-71f36c18111f.png">

Happens for every button in this group except for the last one

<img width="841" alt="screen shot 2018-04-10 at 3 32 36 pm" src="https://user-images.githubusercontent.com/19267771/38579247-6aa8612c-3cd4-11e8-98bc-0a770577e2c1.png">

**Comment by werebus** [comment]
It's because they are `<a>` elements with a `<button>` inside of them where the `a` is slightly larger than the `button`:

https://github.com/umts/stop-project/blob/5020223a3a049e9f3d5e1fa85ace5f2ab79eabff/app/views/bus_stops/by_route.haml#L6-L7

When you hover over the `button`, that hover state also gets propagated to the `a`, and "links" in this app get `text-decoration: underline` on hover.

[Bootstrap docs](https://getbootstrap.com/docs/4.0/components/buttons/#button-tags) say that you can achieve the same effect by putting the `btn*` cleasses on the `a` directly. Although, when I tried it in the browser, it looked...different.
