### ISSUE TITLE
Add descriptive text from field guide

### ISSUE THREAD

**Issue by sherson** [umts/stop-project#52]
A line or two of text describing what each field is

**Comment by sherson** [comment]
Another option is to create a simple help page with the descriptive text from the field guide.

**Comment by werebus** [comment]
"tooltips" ?

**Comment by Anbranin** [comment]
I thought it best not to do Javascript like that until we had the time to test it on iPhones and Androids before deploying. Then again, that's only because I've never written Javascript fr a rails app that was primarily being used by mobile users. If you know more than I do and are sure it's fine we can go down that route.

**Comment by dfaulken** [comment]
I don't actually see JS mentioned in the request, and I don't think it's needed. I think literal lines of text would be fine in this case.

**Comment by dfaulken** [comment]
@sherson is this required to be done before the general rewrite (i.e. ASAP)? If not, it's just another layer of functionality we have to write only to rewrite a week later.

**Comment by sherson** [comment]
^ Correct, it does not need to be done before Monday (since the users will, in theory, also have the printed guide), but someone (I forget who) suggested that a simple help page would be super quick, and we all agreed that'd also be fine. 

Whether it's enhanced later can be decided later.

![enhance](https://i.imgur.com/FuAgGuS.png)

https://youtu.be/KiqkclCJsZs

**Comment by sherson** [comment]
(yeah yeah not the same kind of enhance, but that scene always makes me laugh)
